[ids]
05ac:0250

[main]
# Swap: F-row <-> multimedia.
f1  = brightnessdown
brightnessdown = f1
f2  = brightnessup
brightnessup = f2
f3  = prog1
prog1 = f3
f4  = prog2
prog2 = f4
f5  = kbdillumdown
kbdillumdown = f5
f6  = kbdillumup
kbdillumup = f6
f7  = previoussong
previoussong = f7
f8  = playpause
playpause = f8
f9  = nextsong
nextsong = f9
f10 = mute
mute = f10
f11 = volumedown
volumedown = f11
f12 = volumeup
volumeup = f12

rightcontrol = layer(fkeys)

[fkeys]
f1 = f1
f2 = f2
f3 = f3
f4 = f4
f5 = f5
f6 = f6
f7 = f7
f8 = f8
f9 = f9
f10 = f10
f11 = f11
f12 = f12
